Repository DeveloperAcademy-POSTECH/MC3_Uniuni, pull requests merged in 2023-07, with the labels that each got.

#5 Feat/jun/3-connect-firebase
  .gitignore
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/BeerChat.entitlements
  BeerChat/Models/User.swift
  BeerChat/Models/UserManager.swift
  BeerChat/System/BeerChatApp.swift
  BeerChat/Views/Entry/EntryView.swift
  BeerChat/Views/Main/Profile/ProfileView.swift
Labels: feat

#9 Feat/sol/2 create keywords seleted view
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Models/Keywords.swift
  BeerChat/System/BeerChatApp.swift
  BeerChat/Views/KeywordSelection/KeywordListVIew.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/KeywordSelection/keywordGridView.swift
Labels: view

#17 View: Add MatchingProfileView
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
Labels: view

#18 Feat/sol/10 matchingview 구현
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Models/UserManager.swift
  BeerChat/Views/KeywordSelection/KeywordListVIew.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/KeywordSelection/keywordGridView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: feat, view

#22 feat: Link matching + matchingProfile
  BeerChat/Views/Main/MainView.swift
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: feat

#21 Feat/jun/6 add signin view
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Models/KeyboardManager.swift
  BeerChat/Models/PageManager.swift
  BeerChat/Models/UserManager.swift
  BeerChat/Views/ContentView.swift
  BeerChat/Views/Entry/EmailVerifyView.swift
  BeerChat/Views/Entry/EntryView.swift
  BeerChat/Views/Main/Profile/ProfileView.swift
  BeerChat/Views/Splash/SplashView.swift
Labels: feat

#24 Feat/sol/15 matching + chatroom 연결
  BeerChat/Models/ChatRoomManager.swift
  BeerChat/Views/Main/Chat/ChatListView.swift
  BeerChat/Views/Main/MainView.swift
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: feat, view

#26 Feat/sol/25 chatroom manager 기능추가
  .swiftlint.yml
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Models/ChatRoomManager.swift
  BeerChat/Models/FireStoreManager.swift
  BeerChat/System/BeerChatApp.swift
  BeerChat/Views/Components/ChatBubble.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/KeywordSelection/keywordGridView.swift
  BeerChat/Views/Main/Chat/ChatListView.swift
  BeerChat/Views/Main/Chat/ChatRoom/ChatView.swift
  BeerChat/Views/Main/MainView.swift
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: feat

#27 view: Add custom grid keyword view
  BeerChat/Views/KeywordSelection/KeywordListVIew.swift
  BeerChat/Views/KeywordSelection/keywordGridView.swift
Labels: view

#29 feat: replace userid to currentUser.userid
  BeerChat/Models/ChatRoomManager.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: fix

#30 feat: limit category keyword
  BeerChat/Views/KeywordSelection/KeywordListVIew.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: feat

#32 View/sol/31 edit total view detail
  BeerChat/Resources/Assets.xcassets/DummyProfile.imageset/Contents.json
  BeerChat/Resources/Assets.xcassets/DummyProfile.imageset/Rectangle 115.png
  BeerChat/Resources/Assets.xcassets/DummyProfile.imageset/Rectangle 116.png
  BeerChat/Resources/Assets.xcassets/DummyProfile.imageset/Rectangle 117.png
  BeerChat/Views/KeywordSelection/KeywordListVIew.swift
  BeerChat/Views/KeywordSelection/KeywordSelectionView.swift
  BeerChat/Views/KeywordSelection/keywordGridView.swift
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: view

#36 fix: fix error in navigation
  BeerChat.xcodeproj/project.pbxproj
  BeerChat/Models/ChatRoomManager.swift
  BeerChat/Models/UserManager.swift
  BeerChat/System/BeerChatApp.swift
  BeerChat/Views/Entry/EmailVerifyView.swift
  BeerChat/Views/Entry/EntryView.swift
  BeerChat/Views/Main/Chat/ChatListView.swift
  BeerChat/Views/Main/Chat/ChatRoom/ChatView.swift
  BeerChat/Views/Main/MainView.swift
  BeerChat/Views/Main/Matching/MatchingProfileView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: fix

#38 37 fix chatroom error
  BeerChat/Models/ChatRoomManager.swift
  BeerChat/Models/FireStoreManager.swift
  BeerChat/Views/Main/Chat/ChatListView.swift
  BeerChat/Views/Main/MainView.swift
  BeerChat/Views/Main/Matching/MatchingView.swift
Labels: fix
